services:
  app:
    build:
      context: .
    image: invoiceninja/invoiceninja-debian:${TAG:-latest}
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      # - ./php/php.ini:/usr/local/etc/php/conf.d/invoiceninja.ini:ro
      # - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/invoiceninja.conf:ro
      # - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - app_public:/var/www/html/public
      - app_storage:/var/www/html/storage
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8023}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - app_public:/var/www/html/public:ro
      - app_storage:/var/www/html/storage:ro
    depends_on:
      app:
        condition: service_healthy

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

  db-backup:
    image: tiredofit/db-backup
    restart: unless-stopped
    volumes:
      - ./backups:/backup
    environment:
      DB01_TYPE: mysql
      DB01_HOST: mysql
      DB01_NAME: ${DB_DATABASE}
      DB01_USER: ${DB_USERNAME}
      DB01_PASS: ${DB_PASSWORD}
      DB01_BACKUP_LOCATION: FILESYSTEM
      DB01_BACKUP_INTERVAL: 1440
      DB01_BACKUP_BEGIN: "0 0 * * *"
      DB01_CLEANUP_TIME: 8640
      DB01_COMPRESSION: GZ
      DB01_GZ_RSYNCABLE: "TRUE"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  app_public:
    driver: local
  app_storage:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local
  backups:
    driver: local
